{"uuid":"23649f8c-58d3-4847-a323-3e009801d4df","historyId":"3e2da0e441e54a76f6bbf71b3bc56fc6","fullName":"Pays.posfinaltesting.StayTest.StayOrder_Cash_RefundItemWise_SelectRefund","labels":[{"name":"package","value":"Pays.posfinaltesting.StayTest"},{"name":"testClass","value":"Pays.posfinaltesting.StayTest"},{"name":"testMethod","value":"StayOrder_Cash_RefundItemWise_SelectRefund"},{"name":"parentSuite","value":"Suite"},{"name":"suite","value":" Cash_ItemwiseRefundPaymentTest"},{"name":"subSuite","value":"Pays.posfinaltesting.StayTest"},{"name":"host","value":"Pratik"},{"name":"thread","value":"23280@Pratik.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Process Item-wise Refund"},{"name":"feature","value":"Refund Management"},{"name":"feature","value":"Order Processing and Refunds"},{"name":"epic","value":"Stay Order Management"},{"name":"severity","value":"critical"}],"links":[],"name":"StayOrder_Cash_RefundItemWise_SelectRefund","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Cash Item-wise Refund failed expected [true] but found [false]","trace":"java.lang.AssertionError: Cash Item-wise Refund failed expected [true] but found [false]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertTrue(Assert.java:57)\r\n\tat Pays.posfinaltesting.StayTest.StayOrder_Cash_RefundItemWise_SelectRefund(StayTest.java:340)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)\r\n"},"stage":"finished","description":"Performs an item-wise refund for a previously paid cash transaction.","steps":[],"attachments":[{"name":"Screenshot on Failure","source":"16cbf3db-cccf-4f27-9f63-ef1e776a9a1a-attachment"}],"parameters":[],"start":1742400860062,"stop":1742400877769}