{"uuid":"fcb9fefc-8e4d-4a07-869e-fcc2f197960e","historyId":"9dbcc6797cacb97b9728d168d9f7997d","fullName":"Pays.posfinaltesting.OpenOderTest.OpenOrder_Cash_RefundItemWise_SelectRefund","labels":[{"name":"package","value":"Pays.posfinaltesting.OpenOderTest"},{"name":"testClass","value":"Pays.posfinaltesting.OpenOderTest"},{"name":"testMethod","value":"OpenOrder_Cash_RefundItemWise_SelectRefund"},{"name":"parentSuite","value":"Suite"},{"name":"suite","value":" Cash_ItemwiseRefundPaymentTest"},{"name":"subSuite","value":"Pays.posfinaltesting.OpenOderTest"},{"name":"host","value":"Pratik"},{"name":"thread","value":"25176@Pratik.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Refund Processing"}],"links":[],"name":"OpenOrder_Cash_RefundItemWise_SelectRefund","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Cash Item-wise Refund failed expected [true] but found [false]","trace":"java.lang.AssertionError: Cash Item-wise Refund failed expected [true] but found [false]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertTrue(Assert.java:57)\r\n\tat Pays.posfinaltesting.OpenOderTest.OpenOrder_Cash_RefundItemWise_SelectRefund(OpenOderTest.java:302)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)\r\n\tat org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)\r\n\tat org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)\r\n"},"stage":"finished","description":"Select item-wise refund option","steps":[],"attachments":[{"name":"Screenshot on Failure","source":"8a9f58df-7438-42af-b51f-8cb7ce5c415f-attachment"}],"parameters":[],"start":1742294539053,"stop":1742294550878}